import type { SlideData } from '@/shared/types/slide'

const slides: SlideData[] = [
  {
    type: 'cover',
    kicker: 'บท B3 · ตาข่ายนิรภัย',
    title: 'Git',
    sub: 'ปุ่มย้อนกลับให้โค้ด · วิธีทำงานร่วมกับคนอื่น',
  },
  {
    type: 'gitflow',
    scene: 'overview',
    command: '',
    title: 'รู้จัก 4 พื้นที่ของ Git',
    sub: 'ไฟล์จะเดินทางระหว่างพื้นที่เหล่านี้เมื่อใช้คำสั่ง',
  },
  {
    type: 'gitflow',
    scene: 'init',
    command: 'git init',
    title: 'เริ่มติดตามโฟลเดอร์ด้วย Git',
    sub: 'สร้างที่เก็บประวัติว่าง โดยไฟล์เดิมยังอยู่ที่เดิม',
  },
  {
    type: 'gitflow',
    scene: 'status',
    command: 'git status',
    title: 'ตรวจสถานะก่อนทำต่อ',
    sub: 'ดูว่าไฟล์ไหนเปลี่ยนแล้ว เตรียม commit แล้ว หรือยังเหมือนเดิม',
  },
  {
    type: 'gitflow',
    scene: 'add',
    command: 'git add style.css',
    title: 'เลือกไฟล์ที่จะบันทึก',
    sub: 'git add ย้ายไฟล์เข้าพื้นที่เตรียม แต่ยังไม่สร้าง commit',
  },
  {
    type: 'gitflow',
    scene: 'commit',
    command: 'git commit -m "Add project files"',
    title: 'บันทึกภาพรวมของโฟลเดอร์',
    sub: 'จัดไฟล์เข้าเฟรม แล้วกดชัตเตอร์เพื่อสร้างจุดที่ย้อนกลับมาได้',
  },
  {
    type: 'gitflow',
    scene: 'log',
    command: 'git log --oneline',
    title: 'เปิดดูประวัติที่บันทึกไว้',
    sub: 'รายการเรียงจาก commit ล่าสุดไปหา commit เก่า',
  },
  {
    type: 'gitflow',
    scene: 'recap',
    command: '# edit style.css\n$ git status\n$ git add style.css\n$ git commit -m "Add stylesheet"',
    title: 'วนรอบแก้ไฟล์ · เตรียม · บันทึก',
    sub: 'ดูสถานะ เลือกไฟล์ แล้วสร้าง commit จนสถานะสะอาด',
  },
  {
    type: 'gitflow',
    scene: 'restore',
    command: 'git restore app.js',
    title: 'ย้อนการแก้ไขไฟล์',
    sub: 'เรียกเวอร์ชันล่าสุดที่ commit ไว้กลับมาแทนไฟล์ที่เสียหาย',
  },
  {
    type: 'gitflow',
    scene: 'branch',
    command: 'git branch feature\n$ git switch feature',
    title: 'แยกสายงานแล้วสลับไปทำต่อ',
    sub: 'สร้าง branch feature จาก main แล้วเปลี่ยนสายงานปัจจุบัน',
  },
  {
    type: 'gitflow',
    scene: 'merge',
    command: 'git merge feature',
    title: 'รวมงานจากอีกสาย',
    sub: 'นำ commit ใน feature มารวมบน main',
  },
  {
    type: 'statement',
    title: 'แก้บรรทัดเดียวกันทั้งสองฝั่ง = conflict',
    sub: 'Git รวมให้เองไม่ได้ ถ้าเจอแบบนี้ขอ Claude ช่วยตรวจและแก้ทีละส่วนได้',
  },
  {
    type: 'statement',
    title: 'ก่อนใช้ GitHub ต้องมีบัญชีและล็อกอิน',
    sub: 'Lab จะพาสมัครและเข้าสู่ระบบก่อนลองเชื่อม repository',
  },
  {
    type: 'gitflow',
    scene: 'remote',
    command: 'git remote add origin https://github.com/example/site.git',
    title: 'ตั้งชื่อปลายทางบน GitHub',
    sub: 'origin เป็นชื่อเรียก URL ของ repository ระยะไกล',
  },
  {
    type: 'gitflow',
    scene: 'push',
    command: 'git push origin main',
    title: 'ส่งประวัติขึ้น GitHub',
    sub: 'push ส่ง commit จากเครื่องไปยัง remote โดยยังเก็บสำเนาในเครื่อง',
  },
  {
    type: 'gitflow',
    scene: 'clone',
    command: 'git clone https://github.com/example/site.git',
    title: 'คัดลอก repository มาเริ่มงาน',
    sub: 'clone นำ commit และไฟล์จาก GitHub มาไว้ในเครื่อง',
  },
  {
    type: 'gitflow',
    scene: 'pull',
    command: 'git pull origin main',
    title: 'ดึงงานล่าสุดจาก GitHub',
    sub: 'pull นำ commit ใหม่จาก remote เข้ามาและอัปเดตไฟล์ในเครื่อง',
  },
  {
    type: 'statement',
    title: 'ชีตคำสั่ง Git',
    sub: [
      'git init — ให้ Git เริ่มติดตามโฟลเดอร์ · git status — ดูสถานะไฟล์',
      'git add style.css — เตรียมไฟล์เข้า commit · git commit -m "Add project files" — บันทึก snapshot',
      'git commit -m "Add stylesheet" — บันทึก snapshot · git log --oneline — ดูประวัติ commit แบบย่อ',
      'git restore app.js — คืนไฟล์จาก commit ล่าสุด · git branch feature — สร้างสายงาน feature',
      'git switch feature — สลับไปสายงาน feature · git merge feature — รวม feature เข้าสายงานปัจจุบัน',
      'git remote add origin https://github.com/example/site.git — ตั้งชื่อ URL ปลายทาง',
      'git push origin main — ส่ง commit ขึ้น GitHub',
      'git clone https://github.com/example/site.git — คัดลอก repository ลงเครื่อง',
      'git pull origin main — ดึง commit ล่าสุดจาก GitHub',
    ].join('\n'),
  },
]

export default slides
